name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        users: actions/checkout@v2
        # Install NPM dependencies, cache them correctily
        # and run all Cypress tests
      - name: Cypress run
        users: cypress-io/github-action@v2